directories:
  output: dist-electron
  buildResources: build
appId: com.screenshotos.app
productName: ScreenshotOS
copyright: Copyright © 2025
mac:
  category: public.app-category.utilities
  target:
    - dmg
    - zip
  darkModeSupport: true
  icon: build/icon.icns
  hardenedRuntime: true
  entitlements: build/entitlements.mac.plist
  entitlementsInherit: build/entitlements.mac.plist
dmg:
  contents:
    - x: 130
      'y': 220
    - x: 410
      'y': 220
      type: link
      path: /Applications
files:
  - filter:
      - dist/**/*
      - '!**/*.map'
electronVersion: 36.2.1
